# Generated by Django 4.1.7 on 2023-02-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=30, verbose_name='Пароль пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email пользователя')),
            ],
        ),
    ]
